/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagementsystem;
import java.awt.Dimension;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SeeMonster
 */
public class TrackLoans extends javax.swing.JInternalFrame {

    
        Connection con;
        PreparedStatement ps;
        ResultSet res;
        DefaultTableModel dtm;
        
    /**
     * Creates new form TrackLoans
     */
    public TrackLoans() {
        initComponents();
       // tableLoan.setPreferredSize(new Dimension(1000,400));
        tableLoan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLoan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        textAccount = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();

        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                onLoad(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Track Loans");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tableLoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableLoan);

        jLabel2.setText("Account ID :");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRefresh)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnSearch)
                        .addComponent(btnRefresh))
                    .addComponent(textAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

   public void returnAllRows(){
         int i = 0;
      
            try {
                con = DBConnection.connectToDB();
                Statement st = con.createStatement();
                res = st.executeQuery("select * from loans");
               
                if(!res.next()){
                        dtm.insertRow(0, new String[]{
                        "None",
                        "None",
                        "None",
                        "None",
                        "None",
                        "None",
                        "None"
                        });
                        }
                
                res.beforeFirst();
                while(res.next()){
                   
                    dtm.insertRow(i, new String[]{
                        res.getString(1),
                        res.getString(2),
                        res.getString(3),
                        res.getString(4),
                        res.getString(5),
                        res.getString(6),
                        res.getString(7),
                        res.getString(8)
                     }
                    );
                   
                  i++;  
                }
             
               
             tableLoan.setModel(dtm);
             tableLoan.getColumn("Date-Time").setPreferredWidth(160);
             tableLoan.getColumn("Monthly Payment").setPreferredWidth(120);
             tableLoan.getColumn("Total Payment").setPreferredWidth(120);
             
             st.close();
             res.close();
             con.close();
             
            } catch (SQLException ex) {
                Logger.getLogger(TrackLoans.class.getName()).log(Level.SEVERE, null, ex);
            }
   } 
    
    //When Frame is loaded
    private void onLoad(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_onLoad
        // TODO add your handling code here:
        
         dtm =   (DefaultTableModel)tableLoan.getModel();
                    dtm.setColumnIdentifiers(new String[]{
                    "Loan ID","Account ID","Interest Rate","Year(s)","Amount","Monthly Payment","Total Payment","Date-Time"      
                    });
      
         returnAllRows();
    }//GEN-LAST:event_onLoad

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        
        String accid = textAccount.getText().trim();
        int i = 0;
        try{
            con = DBConnection.connectToDB();
            ps= con.prepareStatement("select * from loans WHERE acc_id=?");
            ps.setString(1, accid);
            res = ps.executeQuery();
            
               
                if(!res.next()){
                        dtm.insertRow(0, new String[]{
                        "None",
                        "None",
                        "None",
                        "None",
                        "None",
                        "None",
                        "None"
                        });
                        }
                
                res.beforeFirst();
                while(res.next()){
                   
                    dtm.insertRow(i, new String[]{
                        res.getString(1),
                        res.getString(2),
                        res.getString(3),
                        res.getString(4),
                        res.getString(5),
                        res.getString(6),
                        res.getString(7),
                        res.getString(8)
                     }
                    );
                   
                  i++;  
                }
             
               
             tableLoan.setModel(dtm);
             tableLoan.getColumn("Date-Time").setPreferredWidth(160);
             tableLoan.getColumn("Monthly Payment").setPreferredWidth(120);
             tableLoan.getColumn("Total Payment").setPreferredWidth(120);
             
             ps.close();
             res.close();
             con.close();
            
        }catch(Exception ex){
          JOptionPane.showMessageDialog(this, ex.getMessage());

        }
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        textAccount.setText("");
        returnAllRows();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLoan;
    private javax.swing.JTextField textAccount;
    // End of variables declaration//GEN-END:variables
}
